version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: kayak-app-prod
    container_name: kayak-app-prod
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_KEY: ${APP_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: kayak-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
