FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    locales \
    zip \
    git \
    curl \
    libzip-dev \
    unzip \
    nodejs \
    npm \
    pgloader

RUN docker-php-ext-install pdo_mysql gd zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN pecl install redis \
    && docker-php-ext-enable redis

WORKDIR /var/www/html

COPY . .

# Instalacja zależności PHP i Node.js
RUN composer install --optimize-autoloader
RUN npm ci

EXPOSE 9000

CMD ["php-fpm"]
