services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: kayak-app
        container_name: kayak-app
        restart: unless-stopped
        working_dir: /var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: ${APP_KEY}
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PASSWORD: null
            REDIS_PORT: 6379
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - redis
        networks:
            - laravel

    # Serwis bazy danych
    db:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        hostname: kayak-map.test
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
          - '3306:3306'
        networks:
            - laravel
    # Serwis Redis
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        networks:
            - laravel

    overpass-api:
      image: wiktorn/overpass-api:latest
      container_name: overpass-api
      restart: unless-stopped
      ports:
        - "8080:80"
      volumes:
        - overpass_data:/db
        - ./overpass_rivers.osm:/app/rivers.osm
      environment:
        - OVERPASS_META=yes
        - OVERPASS_MODE=init
        - OVERPASS_PLANET_URL=file:///app/rivers.osm
        - OVERPASS_RULES_LOAD=10
      networks:
        - laravel

    # Serwis Nginx
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - '443:443'
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ssl/cert.crt:/etc/nginx/ssl/cert.crt
            - ./docker/ssl/cert.key:/etc/nginx/ssl/cert.key
        depends_on:
            - app
        networks:
            - laravel
    phpmyadmin:
      image: phpmyadmin:latest
      container_name: phpmyadmin
      restart: unless-stopped
      ports:
        - "8081:80"
      environment:
        - PMA_HOST=db
        - PMA_PORT=3306
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
        - UPLOAD_LIMIT=512M
      networks:
        - laravel

volumes:
    db_data:

networks:
    laravel:
        driver: bridge
