services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: kayak-app-prod:latest
    container_name: kayak-app-prod
    restart: unless-stopped
    ports:
      - "2222:22"
    environment:
      APP_ENV: production
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_KEY: ${APP_KEY}
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      QUEUE_CONNECTION: redis
      APP_URL: https://wartkinurt.pl
      APP_TIMEZONE: Europe/Warsaw
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      PHP_FPM_PM: dynamic
      PHP_FPM_PM_MAX_CHILDREN: 10
      PHP_FPM_PM_START_SERVERS: 2
      PHP_FPM_PM_MIN_SPARE_SERVERS: 2
      PHP_FPM_PM_MAX_SPARE_SERVERS: 4
      SSH_USER: ${SSH_USER}
      SSH_PASSWORD: ${SSH_PASSWORD}
    volumes:
      - kayak_storage:/var/www/html/storage
      - kayak_logs:/var/www/html/storage/logs
    networks:
      - traefik-public
      - internal
    labels:
      - "traefik.enable=false"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
        reservations:
          memory: 1G

  queue-worker:
    image: kayak-app-prod:latest
    container_name: kayak-queue-prod
    restart: unless-stopped
    command: php artisan queue:work redis --tries=3 --timeout=90
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - kayak_storage:/var/www/html/storage
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M

  scheduler:
    image: kayak-app-prod:latest
    container_name: kayak-scheduler-prod
    restart: unless-stopped
    command: php artisan schedule:work
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      REDIS_HOST: redis
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - kayak_storage:/var/www/html/storage
    networks:
      - internal

  db:
    image: mariadb:latest
    container_name: mariadb-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - kayak_backups:/backups
    ports:
      - "3306:3306"
    networks:
      - internal
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=512M
    networks:
      - internal
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`db.wartkinurt.pl`)"
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.routers.pma.tls.certresolver=myresolver"
      - "traefik.http.services.pma.loadbalancer.server.port=80"

  redis:
    image: redis:alpine
    container_name: redis-prod
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  backup:
    image: tiredofit/db-backup
    container_name: db-backup
    restart: unless-stopped
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_DATABASE}
      - DB_USER=${DB_USERNAME}
      - DB_PASS=${DB_PASSWORD}
      - DB_DUMP_FREQ=10080
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=43200
      - COMPRESSION=gz
      - SPLIT_DB=FALSE
      - CHECKSUM=SHA1
    volumes:
      - kayak_backups:/backup
    networks:
      - internal
  nginx:
    image: nginx:alpine
    container_name: kayak-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - internal
      - traefik-public
    labels:
      - "traefik.enable=true"
      # Główna domena
      - "traefik.http.routers.main.rule=Host(`wartkinurt.pl`)"
      - "traefik.http.routers.main.tls=true"
      - "traefik.http.routers.main.tls.certresolver=myresolver"
      # API
      - "traefik.http.routers.api.rule=Host(`api.wartkinurt.pl`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.wartkinurt.pl`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      # Wspólny port
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

volumes:
  kayak_storage:
    name: kayak_storage
  kayak_logs:
    name: kayak_logs
  db_data:
    name: kayak_db_data
  redis_data:
    name: kayak_redis_data
  kayak_backups:
    name: kayak_backups

networks:
  traefik-public:
    external: true
  internal:
    name: kayak_internal
    driver: bridge
