services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: kayak-app
        container_name: kayak-app
        network_mode: "host"
        restart: unless-stopped
        working_dir: /var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: ${APP_KEY}
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PASSWORD: null
            REDIS_PORT: 6379
            NODE_ENV: development
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./node_modules:/var/www/html/node_modules:cached
            - laravel-storage:/var/www/html/storage
            - ./storage:/var/www/html/storage
        depends_on:
            - db
            - redis
        networks:
            - laravel
        deploy:
            resources:
              limits:
                  cpus: '2'
                  memory: 2G

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ssl/cert.crt:/etc/nginx/ssl/cert.crt
            - ./docker/ssl/cert.key:/etc/nginx/ssl/cert.key
            - laravel-storage:/var/www/html/storage
            - ./storage/app/public:/var/www/html/storage/app/public

        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        networks:
            - laravel

    vite:
        build:
            context: .
            dockerfile: Dockerfile.vite
        container_name: vite
        network_mode: "host"
        volumes:
            - .:/var/www/html:cached
            - ./docker/ssl:/etc/ssl:ro
            - node_modules:/var/www/html/node_modules:cached
        ports:
            - "5173:5173"
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - HOST=0.0.0.0
            - CHOKIDAR_USEPOLLING=true
        networks:
            - laravel
        deploy:
            resources:
                limits:
                    cpus: '3'
                    memory: 4G


volumes:
    kayak-app:
    db_data:
    vendor:
    node_modules:
    laravel-storage:
        driver: local

networks:
    laravel:
        driver: bridge
