services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: kayak-app
        container_name: kayak-app
        restart: unless-stopped
        working_dir: /var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: ${APP_KEY}
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PASSWORD: null
            REDIS_PORT: 6379
            NODE_ENV: development
            PHP_MEMORY_LIMIT: 512M
            PHP_UPLOAD_MAX_FILESIZE: 100M
            PHP_POST_MAX_SIZE: 100M
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - laravel-storage:/var/www/html/storage
        depends_on:
            - db
            - redis
        networks:
            - laravel
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 3G
                reservations:
                    memory: 512M

    # Ultra-optimized Vite container for HMR
    vite:
        build:
            context: .
            dockerfile: docker/vite/Dockerfile.simple
        image: kayak-vite-ultra
        container_name: kayak-vite-ultra
        restart: unless-stopped
        working_dir: /app
        environment:
            # Performance optimization environment
            - NODE_ENV=development
            - DOCKER_ENV=true
            - VITE_APP_URL=${APP_URL:-https://kayak-map.test}
            # File watching optimizations
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=1000
            - CHOKIDAR_BINARY_INTERVAL=2000
            # Vite server configuration
            - VITE_DEV_SERVER_HOST=0.0.0.0
            - VITE_DEV_SERVER_PORT=5173
            - VITE_HMR_PORT=24678
            # Node.js optimizations
            - NODE_OPTIONS="--max-old-space-size=4096"
            - UV_THREADPOOL_SIZE=6
        volumes:
            # Mount entire project directory
            - .:/app:cached
            # Use host node_modules (installed via WSL npm)
            - ./node_modules:/app/node_modules:cached
            # Exclude heavy directories from main mount
            - /app/vendor
            - /app/storage
        # Internal ports only - all traffic through nginx
        expose:
            - "5173"   # Vite dev server (HTTPS)
            - "24678"  # HMR WebSocket
        command: [
            "npm", "run", "dev", "--",
            "--host", "0.0.0.0",
            "--port", "5173",
            "--config", "vite.config.optimized.js",
            "--force"  # Force dependency re-bundling for consistency
        ]
        networks:
            - laravel
        depends_on:
            - app
        # Resource optimization
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 4G  # Increased for better performance
                reservations:
                    memory: 1G
        # Health check for monitoring
        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "https://localhost:5173"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s

    # Nginx optimized for Vite proxy
    nginx:
        image: nginx:latest
        container_name: nginx-optimized
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - .:/var/www/html:ro  # Read-only for better performance
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ssl/cert.crt:/etc/nginx/ssl/cert.crt
            - ./docker/ssl/cert.key:/etc/nginx/ssl/cert.key
            - laravel-storage:/var/www/html/storage
        depends_on:
            - app
            - vite
        networks:
            - laravel
        # Nginx performance optimization
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
                reservations:
                    memory: 128M

    db:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        networks:
            - laravel

volumes:
    db_data:
    laravel-storage:
        driver: local

networks:
    laravel:
        driver: bridge
