version: '3.8'

services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3

    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.4
        ports:
            - "8080:8000"
        environment:
            # Adres URL do pliku .pbf z danymi OSM
            PBF_URL: https://download.geofabrik.de/europe/poland-latest.osm.pbf
            # URL do danych replikacyjnych (opcjonalnie, do aktualizacji bazy danych)
            REPLICATION_URL: https://download.geofabrik.de/europe/poland-updates/
            # Hasło do bazy danych PostgreSQL
            NOMINATIM_PASSWORD: ${NOMINATIM_PASSWORD:-very_secure_password}
            # Opcjonalne style importu, np. address, place, ...
            NOMINATIM_IMPORT_STYLE: address
            # Ilość wątków do użycia podczas importu
            NOMINATIM_THREADS: ${NOMINATIM_THREADS:-4}
            # Ilość wątków do użycia podczas indeksowania
            NOMINATIM_INDEXING_THREADS: ${NOMINATIM_INDEXING_THREADS:-4}
            # Włączenie funkcji odwrotnego geokodowania
            NOMINATIM_ENABLE_REVERSE_LOOKUP: 1
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb
        networks:
            - laravel
        deploy:
            resources:
                limits:
                    memory: 4gb
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/status.php"]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    redis-data:
    nominatim-data:

networks:
    laravel:
        driver: bridge
