services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: kayak-app
        container_name: kayak-app
        restart: unless-stopped
        working_dir: /var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: ${APP_KEY}
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PASSWORD: null
            REDIS_PORT: 6379
            NODE_ENV: development

            PHP_MEMORY_LIMIT: 512M
            PHP_UPLOAD_MAX_FILESIZE: 100M
            PHP_POST_MAX_SIZE: 100M
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./node_modules:/var/www/html/node_modules:cached
            - laravel-storage:/var/www/html/storage
            - ./storage:/var/www/html/storage
        depends_on:
            - db
            - redis
        networks:
            - laravel
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 3G
                reservations:
                    memory: 512M

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ssl/cert.crt:/etc/nginx/ssl/cert.crt
            - ./docker/ssl/cert.key:/etc/nginx/ssl/cert.key
            - laravel-storage:/var/www/html/storage
            - ./storage/app/public:/var/www/html/storage/app/public
        volumes_from:
            -   app:ro
        depends_on:
            - app
            - vite
        networks:
            - laravel

    db:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "8025:8025" # Panel Web MailHog
            - "1025:1025" # SMTP MailHog
    wartkinurt_mysql_testing:
        image: mariadb:11.2
        container_name: wartkinurt_mariadb_testing
        environment:
            MARIADB_DATABASE: wartkinurt_testing
            MARIADB_USER: admin
            MARIADB_PASSWORD: admin123
            MARIADB_ROOT_PASSWORD: admin123
        command: '--default-authentication-plugin=mysql_native_password'
        ports:
            - "3307:3306"
        volumes:
            - mysql_testing_data:/var/lib/mysql
            - ./docker/mariadb/init:/docker-entrypoint-initdb.d

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        networks:
            - laravel

    vite:
        build:
            context: .
            dockerfile: Dockerfile.vite
        container_name: vite
        user: root
        volumes:
            - .:/var/www/html:delegated
            - ./docker/ssl:/etc/ssl:ro
            - node_modules:/var/www/html/node_modules
        ports:
            - "5173:5173"
            - "3001:3000"
        environment:
            - NODE_ENV=development
            - HOST=0.0.0.0
            - VITE_PORT=5173  # Explicitly set Vite port
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=1000
            - WATCHPACK_POLLING=true
        networks:
            - laravel
        deploy:
            resources:
                limits:
                    cpus: '3'
                    memory: 4G

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - UPLOAD_LIMIT=512M
        networks:
            - laravel
    mysqldump:
        image: mysql:8.0
        container_name: mysqldump-tool
        restart: "no"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - ./docker/mysql:/backups
        networks:
            - laravel
        depends_on:
            - db
        entrypoint: [ "tail", "-f", "/dev/null" ]

volumes:
    kayak-app:
    db_data:
    vendor:
    node_modules:
    mysql_testing_data:
    laravel-storage:
        driver: local

networks:
    laravel:
        driver: bridge
