version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: kayak-app
        container_name: kayak-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        env_file:
            - .env.local
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: mariadb:10.6
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
