services:
  - type: web
    name: kayak-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: laravel-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: laravel-redis
          property: port
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: PORT
        value: 8000
    healthCheckPath: /
    buildCommand: |
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: ./start.sh

databases:
  - name: laravel-db
    databaseName: laravel
    user: laravel
    plan: starter

redis:
  - name: laravel-redis
    ipAllowList: []
    plan: starter
