<?php

return [
    'tile_buffer_km' => 2.0,
    'rivers' => [
        ['key' => 'wisla', 'name' => 'Wisła', 'aliases' => ['Vistula'], 'country_code' => 'PL'],
        ['key' => 'odra', 'name' => 'Odra', 'aliases' => ['Oder'], 'country_code' => 'PL'],
        ['key' => 'warta', 'name' => 'Warta', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'bug', 'name' => 'Bug', 'aliases' => ['Western Bug'], 'country_code' => 'PL'],
        ['key' => 'narew', 'name' => 'Narew', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'notec', 'name' => 'Noteć', 'aliases' => ['Netze'], 'country_code' => 'PL'],
        ['key' => 'pilica', 'name' => 'Pilica', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'wieprz', 'name' => 'Wieprz', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'san', 'name' => 'San', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'bobr', 'name' => 'Bóbr', 'aliases' => ['Bober'], 'country_code' => 'PL'],
        ['key' => 'lyna', 'name' => 'Łyna', 'aliases' => ['Lyna'], 'country_code' => 'PL'],
        ['key' => 'drweca', 'name' => 'Drwęca', 'aliases' => ['Drewenz'], 'country_code' => 'PL'],
        ['key' => 'brda', 'name' => 'Brda', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'wda', 'name' => 'Wda', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'obra', 'name' => 'Obra', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'drawa', 'name' => 'Drawa', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'prosna', 'name' => 'Prosna', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'bzura', 'name' => 'Bzura', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'dunajec', 'name' => 'Dunajec', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'poprad', 'name' => 'Poprad', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'raba', 'name' => 'Raba', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'skawa', 'name' => 'Skawa', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'nida', 'name' => 'Nida', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'biebrza', 'name' => 'Biebrza', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'czarna-hancza', 'name' => 'Czarna Hańcza', 'aliases' => ['Black Ančia'], 'country_code' => 'PL'],
        ['key' => 'krutynia', 'name' => 'Krutynia', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'rega', 'name' => 'Rega', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'parseta', 'name' => 'Parsęta', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'ina', 'name' => 'Ina', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'slupia', 'name' => 'Słupia', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'lupawa', 'name' => 'Łupawa', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'wieprza', 'name' => 'Wieprza', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'radunia', 'name' => 'Radunia', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'gwda', 'name' => 'Gwda', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'biala', 'name' => 'Biała', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'liswarta', 'name' => 'Liswarta', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'mala-panew', 'name' => 'Mała Panew', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'klodnica', 'name' => 'Kłodnica', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'nysa-klodzka', 'name' => 'Nysa Kłodzka', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'bystrzyca', 'name' => 'Bystrzyca', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'kaczawa', 'name' => 'Kaczawa', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'kwisa', 'name' => 'Kwisa', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'nysa-luzycka', 'name' => 'Nysa Łużycka', 'aliases' => ['Neisse'], 'country_code' => 'PL'],
        ['key' => 'rospuda', 'name' => 'Rospuda', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'pisa', 'name' => 'Pisa', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'omulew', 'name' => 'Omulew', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'orzyc', 'name' => 'Orzyc', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'suprasl', 'name' => 'Supraśl', 'aliases' => [], 'country_code' => 'PL'],
        ['key' => 'swina', 'name' => 'Świna', 'aliases' => ['Swinoujscie waterway'], 'country_code' => 'PL'],
        ['key' => 'swider', 'name' => 'Świder', 'aliases' => [], 'country_code' => 'PL'],
    ],
];
