const weatherDescriptions = {
    clearsky_day: 'Bezchmurnie',
    clearsky_night: 'Bezchmurnie',
    clearsky_polartwilight: 'Bezchmurnie',
    fair_day: 'Pogodnie',
    fair_night: 'Pogodnie',
    fair_polartwilight: 'Pogodnie',
    partlycloudy_day: 'Częściowe zachmurzenie',
    partlycloudy_night: 'Częściowe zachmurzenie',
    partlycloudy_polartwilight: 'Częściowe zachmurzenie',
    cloudy: 'Pochmurno',
    rainshowers_day: 'Przelotne opady deszczu',
    rainshowers_night: 'Przelotne opady deszczu',
    rainshowers_polartwilight: 'Przelotne opady deszczu',
    rainshowersandthunder_day: 'Przelotne opady deszczu z burzą',
    rainshowersandthunder_night: 'Przelotne opady deszczu z burzą',
    rainshowersandthunder_polartwilight: 'Przelotne opady deszczu z burzą',
    sleetshowers_day: 'Przelotne opady deszczu ze śniegiem',
    sleetshowers_night: 'Przelotne opady deszczu ze śniegiem',
    sleetshowers_polartwilight: 'Przelotne opady deszczu ze śniegiem',
    snowshowers_day: 'Przelotne opady śniegu',
    snowshowers_night: 'Przelotne opady śniegu',
    snowshowers_polartwilight: 'Przelotne opady śniegu',
    rain: 'Deszcz',
    heavyrain: 'Silny deszcz',
    heavyrainandthunder: 'Silny deszcz z burzą',
    sleet: 'Deszcz ze śniegiem',
    snow: 'Śnieg',
    snowandthunder: 'Śnieg z burzą',
    fog: 'Mgła',
    sleetshowersandthunder_day: 'Przelotne opady deszczu ze śniegiem i burzą',
    sleetshowersandthunder_night: 'Przelotne opady deszczu ze śniegiem i burzą',
    sleetshowersandthunder_polartwilight: 'Przelotne opady deszczu ze śniegiem i burzą',
    snowshowersandthunder_day: 'Przelotne opady śniegu z burzą',
    snowshowersandthunder_night: 'Przelotne opady śniegu z burzą',
    snowshowersandthunder_polartwilight: 'Przelotne opady śniegu z burzą',
    rainandthunder: 'Deszcz z burzą',
    sleetandthunder: 'Deszcz ze śniegiem i burzą',
    lightrainshowersandthunder_day: 'Lekkie przelotne opady deszczu z burzą',
    lightrainshowersandthunder_night: 'Lekkie przelotne opady deszczu z burzą',
    lightrainshowersandthunder_polartwilight: 'Lekkie przelotne opady deszczu z burzą',
    heavyrainshowersandthunder_day: 'Silne przelotne opady deszczu z burzą',
    heavyrainshowersandthunder_night: 'Silne przelotne opady deszczu z burzą',
    heavyrainshowersandthunder_polartwilight: 'Silne przelotne opady deszczu z burzą',
    lightrainshowers_day: 'Lekkie przelotne opady deszczu',
    lightrainshowers_night: 'Lekkie przelotne opady deszczu',
    lightrainshowers_polartwilight: 'Lekkie przelotne opady deszczu',
    heavyrainshowers_day: 'Silne przelotne opady deszczu',
    heavyrainshowers_night: 'Silne przelotne opady deszczu',
    heavyrainshowers_polartwilight: 'Silne przelotne opady deszczu',
    lightsleetshowers_day: 'Lekkie przelotne opady deszczu ze śniegiem',
    lightsleetshowers_night: 'Lekkie przelotne opady deszczu ze śniegiem',
    lightsleetshowers_polartwilight: 'Lekkie przelotne opady deszczu ze śniegiem',
    heavysleetshowers_day: 'Silne przelotne opady deszczu ze śniegiem',
    heavysleetshowers_night: 'Silne przelotne opady deszczu ze śniegiem',
    heavysleetshowers_polartwilight: 'Silne przelotne opady deszczu ze śniegiem',
    lightsnowshowers_day: 'Lekkie przelotne opady śniegu',
    lightsnowshowers_night: 'Lekkie przelotne opady śniegu',
    lightsnowshowers_polartwilight: 'Lekkie przelotne opady śniegu',
    heavysnowshowers_day: 'Silne przelotne opady śniegu',
    heavysnowshowers_night: 'Silne przelotne opady śniegu',
    heavysnowshowers_polartwilight: 'Silne przelotne opady śniegu',
    lightrain: 'Lekki deszcz',
    lightsleet: 'Lekki deszcz ze śniegiem',
    lightsnow: 'Lekki śnieg',
    heavysleet: 'Silny deszcz ze śniegiem',
    heavysnow: 'Silny śnieg',
};

export default weatherDescriptions;
