name: Build and Push Docker Image

# Workflow uruchamiany ręcznie
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch do zbudowania (np. main, develop)'
        required: true
        default: 'master'
      image_tag:
        description: 'Tag obrazu Docker (np. latest, v1.0.0)'
        required: true
        default: 'latest'
      additional_tags:
        description: 'Dodatkowe tagi oddzielone przecinkami (opcjonalnie)'
        required: false

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: registry.wartkinurt.pl

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check registry reachability
        run: curl --fail --show-error --silent --location --retry 5 --retry-delay 10 --max-time 30 "https://${DOCKER_REGISTRY}/v2/" || test "$?" = "22"

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Prepare tags
        id: prep
        run: |
          MAIN_TAG="${{ github.repository_owner }}/wartkinurt:${{ github.event.inputs.image_tag }}"
          TAGS="${DOCKER_REGISTRY}/${MAIN_TAG}"

          # Dodaj dodatkowe tagi, jeśli są
          if [[ -n "${{ github.event.inputs.additional_tags }}" ]]; then
            IFS=',' read -ra ADDITIONAL_TAGS <<< "${{ github.event.inputs.additional_tags }}"
            for tag in "${ADDITIONAL_TAGS[@]}"; do
              TAGS="${TAGS},${DOCKER_REGISTRY}/${{ github.repository_owner }}/wartkinurt:${tag}"
            done
          fi

          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "Przygotowane tagi: ${TAGS}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.event.inputs.image_tag }}
            VITE_API_URL=https://api.wartkinurt.pl

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
